version = 0.1

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "cognito-auth-system"
resolve_s3 = true
s3_prefix = "cognito-auth-system"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolId=\"us-east-1_Ibp76ZpqU\" CognitoClientId=\"5g48nkghk7pvbdu8joaa2kvdi8\" CognitoRegion=\"us-east-1\" Environment=\"dev\""
image_repositories = []

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.global.parameters]
region = "us-east-1"
